name: github-actions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: testapprobert
          publish-profile: ${{ secrets.AZURE_AUTH_MICROSERVICE }}
          package: .
